### ISSUE TITLE
Opening the same wallet creates additional records

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1330]
### Environment

* Smapp version: any
* Node version: any
* OS: any

### Describe the bug

Having one wallet logged in in Smapp, and then restoring a wallet from file - if we pick the same wallet that is already logged in, it will be added as a second wallet, then we can repeat it. There's no warning that we are opening the same wallet / there's no distinction between the records in the dropdown on the login page, the doubles are not marked/removed. 

### Steps to reproduce

1.  Open smapp and log in with one wallet
2.  backup this wallet to the file 
3.  open existing wallet / settings->restore wallet - choose the backup file you just created
4. try copying the wallet file to another location and open it again, repeat it 

### Expected behavior

If we open the same wallet that is already opened, it should not be possible or at least marked somehow as a double on the login screen. 

### Actual behavior

<img width="1442" alt="Screenshot 2023-07-10 at 01 06 17" src="https://github.com/spacemeshos/smapp/assets/89876259/111516e9-3c4e-4d23-a543-febd9747f9e3">

### Logs
let me know if needed

**Comment by brusherru** [comment]
Aha... I misread the issue and thought that there were duplicates of the same wallet file...
However, after checking it up I found that you mean that it is possible to add there few wallet files which has the same wallet inside...

And I think that we should not fix that because there is no way to clearly understand that it is the same wallet:
1. We can find only the exact copies (by reading each file and comparing strings)
2. Once one of the wallet files is changed (added contact/account) — there will be no way to find copies
3. We may not know the scenario when User really wants to have a copy and then modify it — it will be impossible if we just ignore one of the copies

So I propose to not overcomplicate it.
However, probably we need to add a feature to remove the wallet file from the dropdown and display the full path to the wallet file.
