### ISSUE TITLE
no reward, two pcs and the same node id, different post files

### ISSUE THREAD

**Issue by myth2loki** [spacemeshos/smapp#1451]
at very beginning, I plotted 512GB, and copy them to another pc, then plotted 4t again. final I have 2 PCs with the same smesh id, but different post files. at reward day ,I got nothing.

although I saw it from log. but got nothing, any solution?
Eligible for rewards in layers 8066, 8080, 8285, 8346, 8373, 8376, 8489, 8551, 8583, 8644, 8652, 8712, 8722, 8745, 8891, 8909, 9189, 9214, 9290, 9330, 9334, 9353, 9546, 9569, 9574, 9734, 9768, 9842, 10233, 10248, 10408, 10433, 10673, 10692, 10905, 10921, 10946, 10948, 11040, 11160, 11409, 11412, 11457, 11768, 11770, 11888, 11958, 12013, 12067�

**Comment by brusherru** [comment]
I'm sorry, but if you have published activation twice using the same Smesher ID, then this SmesherID is banned.
The protocol works in this way to avoid some malicious actors publishing the same PoS data more than once thus claiming more rewards.

So the only way for you to Smesh now is to recreate PoS data using a new Smesher ID:
1. clean up your current PoS directory, including `key.bin` file — it contains the SmesherID
2. set up smeshing once again (it will create a new `key.bin` file if it is not exist in the directory)
3. ensure that you got a new SmesherID ;)

When you will create a second PoS data — go through these three steps once again after copying/moving PoS data. ;)

---
Closing the issue since we cannot do anything with it.

**Comment by myth2loki** [comment]
> I'm sorry, but if you have published activation twice using the same Smesher ID, then this SmesherID is banned. The protocol works in this way to avoid some malicious actors publishing the same PoS data more than once thus claiming more rewards.
> 
> So the only way for you to Smesh now is to recreate PoS data using a new Smesher ID:
> 
> 1. clean up your current PoS directory, including `key.bin` file — it contains the SmesherID
> 2. set up smeshing once again (it will create a new `key.bin` file if it is not exist in the directory)
> 3. ensure that you got a new SmesherID ;)
> 
> When you will create a second PoS data — go through these three steps once again after copying/moving PoS data. ;)
> 
> Closing the issue since we cannot do anything with it.

Oh, I got it after many days. but I lost 6t post files. I must replot now, Thank you very much any
