### ISSUE TITLE
Hide left panel for edit smeshing opts screen

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1461]
### Environment

* Smapp version: latest

### Describe the bug

Right now we have to call [dispatch(hideSmesherLeftPanel());
](https://github.com/spacemeshos/smapp/pull/1397/files#diff-2f272b881ae8ff902e02cbd366f81c899b63396572563819304c10f4ebd5e769R504) to avoid to see left side panel for Edit semshing options on the smeshing screen

We need to delete this call, but still hide the left side panel on the Smeshing Edit page 

### Steps to reproduce

1. comment hideSmesherLeftPanel() call 
2. click Edit 
3. see the left-side panel

### Expected behavior

the left side panel should be hidden but don't use dispatch call on the each click

### Actual behavior

we see the panel if don't call hideSmesherLeftPanel fn

**Comment by brusherru** [comment]
Basically, the problem is that we're changing some global (redux) state to hide a part of the component in some particular case. It is fundamentally wrong and then it causes another problem, because once it is hidden — now it is always hidden (nobody sets it back).

Much more effective will be to move this state right into the state of the `SmesherSetup` route (and screen).

Or maybe we can just get rid of this difference on these two screens and that's it? :D
