### ISSUE TITLE
About Smesher ID duplication.

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1464]
I'm asking below questions many times in Discord. But no one answer. So if someone can, please help me.

Q1.
https://user-images.githubusercontent.com/1897530/261271958-ad5c44d0-0fd9-48d5-b72a-66b44ad0f885.png

Am I correct in assuming that nodes that have not been rewarded so far will be able to earn rewards from the next Round if the errors listed here are not present? 

Q2. Please provide specific steps to resolve the issue of duplicate Smesher IDs due to re-creation of PoS data.

I would like to be guided through the steps, not URLs or other links.
Also, I am asked why I recreated the data, but please just explain the steps, as replying to a question with a question will not solve my problem.

Thank you,

**Comment by brusherru** [comment]
Q1. "Genesis config was updated after initializing a node" means that you have changed something in genesis params (time / extra-data or smth else). So your Node cannot sync and smesh well against the Mainnet. Remove the `genesis` prop from your `node-config.7c...json` and restart Smapp.

Q2.
1. First of all you need to ensure that you're using duplicated Smesher ID. To do so you need to check all your key.bin files, for example: `shasum -a256 ./path/to/one/pos-data/key.bin` and compare it with `shasum -a256 ./path/to/another/pos-data/key.bin`
2. If they are not equal — all good. Otherwise...
3. Turn off one of Nodes ASAP (to prevent being banned if it has not happened yet) and check does your identity already was banned or not.
4. If it is banned — then you need to recreate SmesherID and PoS data for all machines (which uses the same banned Smesher ID).
5. If it is not banned — then keep PoS of bigger size, and create another SmesherID and PoS data in another directory / another machine.
6. To create a new SmesherID you just need to NOT have any `key.bin` file in the PoS data directory. It will be created automatically. When it will be created you can ensure that it is a new one (see first step) without waiting to finish PoS initialization.

**Comment by hryksbt** [comment]
Thanks.

Q1. I was asking if that error was shown, but all my nodes were not shown after updated to 1.0.18.

Q2. Is this an investigation of duplication among multiple PCs and nodes?
When I recreated the PoS data, I deleted the key.bin file.
I am assuming that as long as this file is deleted, the re-created PoS data will not use duplicate IDs, is this correct?
Also, if I delete key.bin, won't the PoS data I have created so far be wasted?

**Comment by brusherru** [comment]
> Is this an investigation of duplication among multiple PCs and nodes?

We fined one of the possible problems in Smapp v1.0.18
There are also cases when the User may accidentally reuse the same identity.
We're working on how to help Users avoid shooting themselves in their feet.
However, if you're doing everything right, don't cut corners, and follow all recommendations, there should be no problems.

**The basic recommendation: if you want to create another PoS data (for smeshing on another machine/node) — ensure that you've moved previous PoS directory entirely, and you have a different key.bin file in the newly created directory.**

> Also, if I delete key.bin, won't the PoS data I have created so far be wasted?

Correct. So don't delete it if you're using the PoS data.

--

I'm closing the issue. GitHub is not the best place for such questions and non-tech discussions.
It's for bug reports, feature requests, etc. Otherwise, we'll end up with a mess in Github issues.
So please, next time ask questions in Discord. If nobody helps you — mention someone from the Spacemesh team ;)

**Comment by hryksbt** [comment]
Hello, I'm very clear because your kindness support.
Sometime no one answer in discord. I asked this 3 4 times.
I could get now. I accept ticket closing. thanks.

Outlook for iOS<https://aka.ms/o0ukef> を入手
________________________________
差出人: Kirill Shumilov ***@***.***>
送信日r: Saturday, August 19, 2023 10:13:08 PM
宛先: spacemeshos/smapp ***@***.***>
CC: Hiroyuki Shibata ***@***.***>; Author ***@***.***>
件名: Re: [spacemeshos/smapp] About Smesher ID duplication. (Issue #1464)


Closed #1464<https://github.com/spacemeshos/smapp/issues/1464> as completed.

―
