### ISSUE TITLE
Smapp force terminated.

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1490]
### Environment

* Smapp version: 1.1.2
* OS: Ubuntu 22

### Describe the bug

After a few hours of starting Smapp, it is forced to terminate.

### Steps to reproduce

1.  Start Smapp
2.  A few hours elapsed
3.  Smapp force terminated

### Expected behavior

Smapp stays up and running

### Actual behavior

Force terminated in a few hours.
Because of this, this node has been unable to earn mining rewards for a long time.

### Logs

[log.txt.zip](https://github.com/spacemeshos/smapp/files/12517991/log.txt.zip)

**Comment by hryksbt** [comment]
Can someone check and fix?

**Comment by brusherru** [comment]
@hryksbt Sadly there is nothing interesting in these logs.

Could you check the latest Smapp v1.1.9 and tell me if it is still actual?
Then please upload app-logs, and it will be helpful if you will take a look at process CPU and RAM consumption (and mb take a profiler snapshot). Otherwise, please close the issue.

**Comment by hryksbt** [comment]
@brusherru It is still occurred in 1.1.9.
CPU load is mostly 100% and RAM is about 3GB used that total is 16GB.
[1.1.8-applog.txt](https://github.com/spacemeshos/smapp/files/12662328/1.1.8-applog.txt)
This is app log of 1.1.8-pre-release. When I get 1.1.9 stable one,I will attache here.
While I get this, please check this.

**Comment by hryksbt** [comment]
[applog-1.1.9.txt](https://github.com/spacemeshos/smapp/files/12662601/applog-1.1.9.txt)
Here is 1.1.9 applog.

Thanks.

**Comment by brusherru** [comment]
@hryksbt Sadly there are no clues in the logs, and we can't reproduce it.

Could you provide more info:
1. Check out `/var/logs/syslog` and `/var/logs/apport.log`. If you find there is something about Spacemesh app — please attach such a part. Since the system terminates Smapp for some reason — one of these log files should contain an actual error (most likely apport.log).
2. Your system specs (CPU, GPU)
3. Your PoS data is created, HDD/SSD is always accessible (and it is not an external drive that goes sleep sometimes), and you're smeshing. Right?

**Comment by hryksbt** [comment]
1. I found below error in /var/log/syslog.

`/var/log/syslog:Sep 20 18:07:39 i7k03-4090 systemd-oomd[826]: Killed /user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-spacemesh_app-2892.scope due to memory pressure for /user.slice/user-1000.slice/user@1000.service being 50.86% > 50.00% for > 20s with reclaim activity`

2. Intel i9-13900K, i5-13600K, RTX4070ti, RTX4080, RTX 4090, RTX3070, RTX3080

3. Yes. Because some PC's disks are including OS.
I have some case like external USB or SATA internal too.
All the same situation.

This is especially occurred only Ubuntu. When epoch round finish, mostly all PCs are down in spite of any OS.
Then start Smapp, Ubuntu will mostly continue to down.

And this is memory space.

_$ free
total used free shared buff/cache available
Mem: 16217676 5460576 169524 20084 10587576 10392104
Swap: 2097148 752852 1344296_

This has lots of free space.

I wish this issue will be solved until next round....

**Comment by hryksbt** [comment]
$ free
               total        used        free      shared  buff/cache   available
Mem:        16217676     5460576      169524       20084    10587576    10392104
Swap:        2097148      752852     1344296

**Comment by hryksbt** [comment]
I'm trying to remove swap disk now.
It seems better than before.
I am going to check and then update result.
If this is solution, I recommend to you write remove swap information especially for Ubuntu.

**Comment by brusherru** [comment]
@hryksbt did you find a solution?
It seems like a problem with your environment, not Smapp or go-spacemesh.

Probably something is broken in `/etc/systemd/oomd.conf` or maybe you have some weird policy that allows any app to take up to 50% of memory, which may cause the problem. In the rest, I have no idea what else to check :(

**Comment by hryksbt** [comment]
It works much better after killed swap.
But still I face force termination some time.
Anyway, I will close this.
If I find cause of issue, I might re-open ticket.
