### ISSUE TITLE
Smapp does not display balance properly for some users

### ISSUE THREAD

**Issue by myth2loki** [spacemeshos/smapp#1535]
version: 1.1.11
There has reward on transaction,  but no balance in wallet, how to fix it?

**Comment by brusherru** [comment]
This is also reproducible on 1.1.12, 1.2.0 and 1.2.1
However, this bug is reproducing only on some machines. It does not reproducing all the time.

I guess that something wrong with `AccoundDataQuery` call (mb it fails and defaults to `0`, mb API works incorrect). Because once someone send a coin to the account with "0 balance" it updates to the correct value, so `AccountDataStream` works.
