### ISSUE TITLE
SMAPP freezes when the system starts if the Internet connection is not active.

### ISSUE THREAD

**Issue by GMND** [spacemeshos/smapp#1546]
### Environment

* Smapp version: 1.2.1
* Node version: node-not-started (settings screen, info section)
* OS: Windows 11

### Describe the bug

If the Internet connection with the provider is established later than the application autostarts, the application freezes at the authorization stage. After the Internet connection appears, the application continues to remain inactive and nothing happens as monitored by the task manager.

### Steps to reproduce

1. Activate application autorun in settings.
2. Turn off the PC.
3. Disable the WAN port on the router.
4. Turn on the PC and wait for SMAPP to start.
5. Connect the provider's cable to the WAN port of the router.

On laptops, this problem is also present if the Wi-Fi connection is established with a delay.

### Expected behavior

The warning about the lack of Internet connection when starting the application is not functional.

### Actual behavior

What’s happening now?

To successfully launch the application you have to manually close and restart SMAPP.

**Comment by maparr** [comment]
Confirming that this issue exists: When starting the application with no internet connection and then connecting the PC to the internet afterward, we encounter an infinite loading screen.

**Comment by maparr** [comment]
**The additional case** we should take care of is when the `node-config` is not updated in our server's bucket, resulting in an empty object. This situation can also arise when our server, Firewall, VPN, or similar components cannot ping our server using the `node-config.file` or `networks.json` file.

We are getting [messages from our community](https://discord.com/channels/623195163510046732/1163184178075029574/1163184178075029574) and [here](https://discord.com/channels/623195163510046732/1160639728119451759/1160639728119451759) about the empty `node-config` file after updating to the latest version (versions 1.2.2, 1.2.3, and 1.2.4; we're not sure about other versions).

When the `node-config` file is empty, I tried to reproduce it, but during the update, I had to close `smapp` and finish the process that I opened with the `--discovery` flag. I believe there might be an issue when we cannot download the `node-config` file during an update, or when it's empty, causing problems with an empty `node-config`.

However, when I tried to mock an empty `node-config.json` file, I didn't have any success. Until we have the `genesisID` hash from the `node-config.json` file, our application doesn't load properly.

Since I can't reproduce it properly, it could be any error from our clients. Up to this point, I think we should have a modal that appears when we cannot download `networks.json` or `node-config.json`, preventing the app from working properly.

Maybe implement a timeout after 5 minutes of retries, which would describe the error. We're not sure if we will always get 404/500 errors from our bucket on the `node-config.json` request or it will be 200/304 with empty object.

Additionally, we may need to validate the `node-config.json` file to determine if it's a valid JSON or not. Currently, it results in an infinite loading screen.

I created for test [gist](https://gist.github.com/maparr/435947d87c1ead7068ec5d304a1cb05e) , u can up the server on the port 3000 and internally in the networks file for example, point to the 8000 port and play with responses on different routes.

**Comment by brusherru** [comment]
Just for the protocol, this [additional case](https://github.com/spacemeshos/smapp/issues/1546#issuecomment-1774093657) is not related to the topic: Users in the reports have not just empty config files, but files with partially allocated space (~4kb of null bytes). Most likely they encountered some other problem with I/O or race condition (writing the same file twice simultaneously).
