### ISSUE TITLE
"Node Error" as I just installed Spacemesh

### ISSUE THREAD

**Issue by benirango** [spacemeshos/smapp#1652]
### Environment

* Smapp version: guess it is "v1.3.6"
* Node version: v0.x.xx, nothing appears in the "Info Section", just a blank. Getting "v1.3.6" at the bottom of my app, I guess it is the app version.
* OS: macOS High Sierra (10.13.6) (with 3,06 GHz Intel Core 2 Duo, 12 Go 1067 MHz DDR3, ATI Radeon HD 4670 256 Mo)
 
### Describe the bug

I just installed Spacemesh. After saving my wallet's infos, I got on the main page of the Spacemesh App.
I cannot proceed xith the "Proof of Space Status" because my Node is not connected (it flashes red indeed).
When I go to the Network section, a red written message says : "THE SPACEMESH NODE SOFTWARE HAS UNEXPECTEDLY QUIT. CLICK ON 'RESTART NODE' TO START IT.".
Restarting the node is not effective.
- My firewall settings seem OK
- I am using a 2009 iMac, which I just updated to High Sierra 10.13.6. Thus, not sure how to update the GPU Drivers as commanded.
- I see some ERROR and FAILED messages on my logfile, I guess it is for the worst.

I looked at Discord, but did not find a similar case. I do not know how to proceed, this might be because of my computer.

![Proof 1](https://github.com/spacemeshos/smapp/assets/124165658/6fe80120-914a-4964-aa8e-d84bfadf931e)
![Proof 2](https://github.com/spacemeshos/smapp/assets/124165658/2da35d8d-c53f-4b75-b363-72af8c8cc2ed)

### Logs

Here are my `app-logs.txt` and my `spacemesh-log.txt` :

[app-log.1.3.6.txt](https://github.com/spacemeshos/smapp/files/14058935/app-log.1.3.6.txt)
[spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/smapp/files/14058936/spacemesh-log-7c8cef2b.txt)

---> In advance, thanks a lot... I would really like to be part of this Spacemesh adventure ! :)

**Comment by monikasmolarek** [comment]
Dear @benirango, based on your logs: 
```
dyld: Library not loaded: @rpath/libpost.dylib
  Referenced from: /Applications/Spacemesh.app/Contents/node/go-spacemesh
  Reason: no suitable image found.  Did find:
	/Applications/Spacemesh.app/Contents/node/libpost.dylib: cannot load 'libpost. dylib' (load command 0x80000034 is unknown)
	/Applications/Spacemesh.app/Contents/node/libpost.dylib: stat() failed with errno=1
```
Your node will not start, because it cannot load the libpost.dylib. I would think of 3 possible reasons: 

1. Please check the latest official Smapp release and make sure your system does not block any process, can access and allows loading the `/Applications/Spacemesh.app/Contents/node/libpost.dylib`
` errno=1` corresponds to the error constant EPERM, which stands for "Operation not permitted." This error occurs when a program tries to perform an operation that is beyond its permission level. 

2. If the first suggestion doesn’t help, then I'm afraid that you might not be able to run Smapp or the go-spacemesh node with your `ATI Radeon HD 4670 256 Mo` as it does not seem to support openCL. There are quite limited and low-quality results in Googling about the OpenCL, but you can try to dig more and maybe find the solution, knowing that OpenCL support is required. Keep in mind that in general, to be able to generate the POS data, you will need a much stronger GPU. 

3. Your OS version is outdated and does not seem to be compatible anymore with the latest MacOS/iOS system changes and therefore our application and its dependencies.
`load command 0x80000034 is unknown` corresponds to LC_DYLD_CHAINED_FIXUPS, a part of the dynamic linker system, which was introduced to support newer features in the MacOS. High Sierra might not support this newer load command. 

@pigmej or @brusherru please correct me if I'm wrong. 
I would suggest closing this issue as it's not related to Smapp.
