### ISSUE TITLE
Smapp not talking to already-running node

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#1674]
### Environment

* Smapp version: 1.3.10
* Node version: 1.3.10
* OS: Ubuntu 22.04

### Describe the bug

If Smapp is started when a node process is already running on the default ports, it should successfully talk to that process without attempting to launch a new node. For some reason, it briefly talked to the running node and read the node data, then incorrectly reports that the node unexpectedly quit (it didn't).

### Steps to reproduce

1. Install, run, and fully sync go-spacemesh
2. Install and run Smapp
3. Restore an existing, spawned wallet account

### Expected behavior

Should work fine while talking to running node

### Actual behavior

See above. Note that the go-spacemesh process is still running fine, I can still talk to it using the GRPC API, and it's progressed several layers beyond what Smapp displays. If I restart Smapp, it's briefly okay, then reports the same error again.

![image](https://github.com/spacemeshos/smapp/assets/3316532/1f5ff46e-d4c3-4fe9-9a98-9b1c1908f138)

### Logs

[app-log.1.3.10.txt](https://github.com/spacemeshos/smapp/files/14315933/app-log.1.3.10.txt)

**Comment by pigmej** [comment]
It's not supported use case.

**Comment by pigmej** [comment]
Smapp needs currently to spawn it's own process.

1) it needs to parse logs
2) It needs to manage it life cycle

The case that you described was the "remote node" case that was disabled before the mainnet.

**Comment by lrettig** [comment]
@brusherru this used to work - in fact it worked for a while, and I used to do this reliably. When/why did this change? Is it because of node parsing?

**Comment by lrettig** [comment]
> The case that you described was the "remote node" case that was disabled before the mainnet.

This is a local node, it has nothing to do with remote node. And I ran this way successfully many times post-mainnet.

Even assuming what @pigmej says is true - hypothetically - there's still something wrong here. Smapp is clearly talking to the already-running local node: you can see it in the connected peers data above, and I can see the grpc calls in the node's log. Then it reports that the node dies, even though it hasn't.

Is it trying to launch another node? It shouldn't if there's already one running. And if it really cannot talk to a node that it doesn't manage, then it should totally refuse to talk to another running node at all.

**Comment by pigmej** [comment]
It's remote in meaning of smapp. Smapp expects to run its own node.

Remote node was the feature where smapp could talk to any node via API only and don't expect it to be a managed subprocess of smapp.

Smapp needs log parsing now to display the status properly (node cache, tortoise load etc).

From a smapp perspective it's a "remote node" when you run another.

And yes, smapp will try to launch a new node, which will fail because of ports being already used. So then weird bugs will show up as you reported today.

The feature here is sadly not supported pretty much since the mainnet.

The next gen app will definitely support that use case.

But yes the error message should be more clear.

**Comment by pigmej** [comment]
It's remote in meaning of smapp. Smapp expects to run its own node.

Remote node was the feature where smapp could talk to any node via API only and don't expect it to be a managed subprocess of smapp.

Smapp needs log parsing now to display the status properly (node cache, tortoise load etc).

From a smapp perspective it's a "remote node" when you run another.

And yes, smapp will try to launch a new node, which will fail because of ports being already used.

The feature here is sadly not supported pretty much since the mainnet.

But yes the error message should be more clear.

**Comment by Hattrix3** [comment]
can i get your perspecitive on why my node needs to restart all the time?
[spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/smapp/files/14628527/spacemesh-log-7c8cef2b.txt)
 here is my log. protocols are wrong. I hope this is a quick fix?

> It's remote in meaning of smapp. Smapp expects to run its own node.
> 
> Remote node was the feature where smapp could talk to any node via API only and don't expect it to be a managed subprocess of smapp.
> 
> Smapp needs log parsing now to display the status properly (node cache, tortoise load etc).
> 
> From a smapp perspective it's a "remote node" when you run another.
> 
> And yes, smapp will try to launch a new node, which will fail because of ports being already used. So then weird bugs will show up as you reported today.
> 
> The feature here is sadly not supported pretty much since the mainnet.
> 
> The next gen app will definitely support that use case.
> 
> But yes the error message should be more clear.

**Comment by Hattrix3** [comment]
Not closed still not earning
