### ISSUE TITLE
FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly

### ISSUE THREAD

**Issue by msmmi** [spacemeshos/smapp#279]
I am using debian with fuxbox 10. I am facing the following error when using the command : smapp.

FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Spacemesh/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

**Comment by avive** [comment]
@msmmi what exactly are you trying to do? Spacemesh 0.1 haven't launched yet so smapp can't run just yet.

**Comment by avive** [comment]
@msmmi  thanks for reporting this issue - we are in a middle of a sprint to code complete the Spacemesh 0.1 App for Windows and OS X first because as much as we ❤️linux - and beleive me - we do - the vast majority of desktops by non techies run windoz :-o We will fix the build issue you reported for linux promptly - we will update here as soon as debian is working.
