### ISSUE TITLE
Cannot re-install

### ISSUE THREAD

**Issue by EmperorXenu** [spacemeshos/smapp#635]
Windows 10. I deleted my installation folder, \spacemesh, and attempted to reinstall it and it gives an error saying the installation failed. I deleted spacemesh entries in the registry and also files in %appdata% but I'm still unable to install the client. I assume there's some remnant I'm missing somewhere but I don't even have the uninstall exe.

**Comment by avive** [comment]
I've observed something similar before when you don't run the uninstall before deleting an installation files. Check for other Spacemesh leftover folders in %appdata% in both `local` and `roaming` dir. They are likely cause new installer to fail. The best way to update is not to remove app folders or to run the uninstaller (which is installed by the installer). If you remove installations manually then you have to make sure all installation data in all locations is cleared. 

It is also likely that you need to remove all Spacemesh registry entries which the installer is considering. It is possible it attempts to run the uninstaller via info in the registry about the older install and fails to find it (it was removed). 

We also need to do a bette job at documenting this and listing all locations which are touched by an installation.

**Comment by avive** [comment]
I think that you may need to do the following:
- Delete Spacemesh entries in your registry.
- Remove all local Spacemesh folder in %appdata%
- Try to install the app again.

Let us know if this resolved your issue. I think this happens if you delete the installation folder without uninstalling smapp from its uninstaller. When Smapp is installed in Windows, it saves an uninstaller to the app installation folder. I think that your installer fails because it reads from the registry info about an old install that doesn't exist anymore and it fails in attempting to uninstall the older installation.

**Comment by EmperorXenu** [comment]
Could you let me know where the registry entries would be exactly? I've removed the ones I could find but the problem persists so I'm probably missing some.

**Comment by avive** [comment]
Any reg entry called `spacemesh`. If you delete your installation folder the installer will get hosed. Another thing to try in the installer that worked for me is to install in a new path and not the default one.

**Comment by brusherru** [comment]
Will be fixed within #499

**Comment by maparr** [comment]
Hi @EmperorXenu, seems for the current version of the Spacemesh app, we resolved this issue. Is it possible to check on your side ?
