### ISSUE TITLE
Configurable NTP servers list

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#674]
In https://github.com/spacemeshos/go-spacemesh/pull/2221, @narayanprusty added support for a configurable list of NTP servers in go-spacemesh. We still need to add support for this to the frontend (so we don't need a [separate smapp release](https://github.com/spacemeshos/smapp/releases/tag/v0.1.6-ntp-fix) for each network).

I think the simplest way to do this would be to auto-detect inside Smapp whether the user is running in mainland China - based on IP address or, as a fallback, by trying to contact one of the non-Chinese NTP servers. If so, the China-based NTP servers list should be passed into go-spacemesh.

CC @avive

**Comment by noamnelke** [comment]
I think there should be a way to configure the list of NTP servers in the SMApp (advanced settings), but I don't think the SMApp should do any fancy auto-detection.

My reasoning is that we want to provide Chinese users with a workaround until this is properly solved in the node. There's no reason that the SMApp should be responsible for this logic, as it would still affect users who install the node directly.

Ultimately, the node should start with a big list of NTP servers and eliminate them based on unresponsiveness or high latency.

Even though I hope this will be resolved in the node soon, I think it's a good idea to allow advanced users to control this setting in the SMApp, so adding the configuration option is not a waste of time anyway.

**Comment by tal-m** [comment]
Why are we using NTP servers at all? This seems like a dangerous trust assumption. I think we should sync time from received blocks and gossip neighbors... (unless we're just using NTP as a sanity check)

**Comment by noamnelke** [comment]
We're currently relying on NTP, but planning to get rid of it. However, implementing this is far from trivial and therefore not considered urgent.

While I agree that it's a dangerous trust assumption, it's not likely to be a viable attack vector in the first year or two due to low network value and high cost of compromising (multiple) NTP servers. It's also a change that would be easy to make post-launch as the solution I have in mind doesn't affect the protocol.

**Comment by lrettig** [comment]
Removing the reliance on NTP in the first place is clearly the way to go, but as you point out Noam that will take some time. I really don't like the idea of needing to do multiple releases every time we release a new testnet, so as a stopgap, I think having Smapp pick the NTP servers is a reasonable workaround.

> I think there should be a way to configure the list of NTP servers in the SMApp (advanced settings), but I don't think the SMApp should do any fancy auto-detection.

Auto-detection seems easy and it seems to me like better UX. We want the app to be friendly, and usable, to non-technical users.

**Comment by noamnelke** [comment]
As I see it, these are the possible steps, some can be skipped or merged:

1. **Allow manually selecting the NTP servers from SMApp config**
2. **Auto-select NTP servers in the SMApp**
3. **Auto-select NTP servers in the node**
4. **Replace NTP**

4 is the long term solution, hard to implement and not urgent, imo. We should do it post-genesis.

Assuming we do 4 post-genesis, I think 3 is a must pre-genesis as it resolves some node stability issues.

Assuming we do 3 pre-genesis, 1 and 2 aren't critical, but if we don't do at least 1 we need a separate SMApp build. Since 1 is very easy to implement and doesn't get deprecated by 3 (only by 4), I think it's worth doing now.

I don't object to doing 2, I just think it competes for SMApp development resources and will be deprecated by 3. It seems to me that we have SMApp tasks that would have a greater impact per user per work required (given that we have very few Chinese Smeshers). I leave it up to you and @avive to decide.

If we do decide to do 2, we can optionally skip 1 and still not require a separate build, but I think it may still be worth doing because it's easy to do and may help work around future issues, plus give users more control.

**Comment by avive** [comment]
I think that we shouldn't do anything related to NTP functionality in Smapp for 0.2 considering we want to finalize it asap and there are still lots to be developed. These are nice features but should be low priority IMO. It is absolutely fine that NTP for now are part of config file so they are configurable by advanced users and we can easily provide a config file that may work behind the great firewall.

**Comment by avive** [comment]
I think that the consensus right now is that config file should include list of NTP servers to use by node. When this is implemented in node, we should add a way to add/edit/remove ntp server from the config via smapp and when user has done so, the ntp servers are going to be provided to the node via startup flag by smapp to override the ones from the config file.
