### ISSUE TITLE
Amounts input

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#681]
# Motivation 
We want to make it easier for users to enter both small and large Smidge amounts in Smapp. 
Current amount inputs are always in Smidge and only accepts integer values. This makes it hard and error prone to enter large amounts such as 1 Smesh. To send 1 Smesh today user has to enter `1000000000000` into the amount field.

# Proposed Solution
There should always be a drop-down widget on the right side of any input text box in Smapp that accepts amounts. e.g. new transaction amount, new transaction gas price, vault daily spending limit. The drop-down should contain 2 options with labels 'Smidge (SMD)' and 'Smesh (SMH)'. The default should be Smidge. The input itself should accept decimal fractions as well as integer so user can for example select 'Smesh' from drop-down and enter `0.5` as the amount.

**Comment by brusherru** [comment]
Oh. I think that this one is closed by #805.
However, we can keep it open until @vomcent will provide us a new design for it and then we'll implement it.

And there will be another issue with big numbers, but we are waiting for the implemented solution of https://github.com/spacemeshos/go-spacemesh/issues/2718 including the new proto interface.

**Comment by avive** [comment]
@vomcent please point us to design in Figma or create one...

**Comment by avive** [comment]
@brusherru here are mocks with the visual design for the amounts:

https://www.figma.com/file/6bbFkIAzVu36bIpUNnMqoy/Smapp-Designs?node-id=9602%3A37522

**Comment by maparr** [comment]
@brusherru  will take this one.

**Comment by brusherru** [comment]
Folks, I don't like the idea of dropdown here.
We have only two options here: SMH / Smidge.

Dropdowns for two options the very ineffective interface.
Let's compare it to the switch button that we have:

Switch button:
1. Aim
2. Click
3. Think (aka User understands that now he will write amount in another units)

Dropdown:
1. Aim
2. Click
3. Think (because we see options, we need to read them and choose one)
4. Aim
5. Click
6. Think (to ensure everything is chosen well)

--
So I propose to close the issue and leave the unit switch button as is ;)

**Comment by oriya** [comment]
Agreed
