### ISSUE TITLE
Display version on main screen

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#718]
We get a lot of screengrabs from users reporting issues such as being unable to connect or sync. One major cause of these issues is when a user runs an older version of smapp. But we can't tell the version from these screengrabs. Could we please display the version of the app on the main screen at all times, eg, in light gray text at the bottom right corner?

**Comment by avive** [comment]
I don't think this feature should be in this sprint as it is not part of the happy flow for the core uses cases. It is part of a bunch of useful features that improve the UX and the feedback process but I think that the focus of this sprint should be to get smeshing and basic wallet flows working with the new api.

**Comment by brusherru** [comment]
@lrettig @IlyaVi @avive

As for me, I'd like a solution in the corner of any screen, because it is easier for the User to find out and copy the version of the app for the bug report.  Moreover, if we'd add an auto-update feature it will be a great place to add the button that runs update or notification that the version is outdated. It will be always visible to the User.
So, how to implement it? In titlebar or in the corner? :)

In both ways, I'd prefer to avoid changing the package.json by any scripts, but if we need to set some information in the title — do it from the main process, by `window.setTitle` method and importing package.json. This also will work for running the app in dev mode.
Is it sounds good, @IlyaVi? Or I miss something?

**Comment by avive** [comment]
Honestly, I never liked this feature too much because its makes the main UI more heavy than it should be with info that is not relevant to the user 90% of the time. 

It is a bit of a hack because we don't have proper error reporting from the app yet which should include an option fo to share a screen shot. 

I think the least evil ui-wise is to display it bottom-left corner of each screen, so it is visible in screen shots but not intrusive or attention grabbing. 

I also don't think that showing it in the menu bar is a good idea because it is not visible in full screen mode. 

Something like what is in the mock will be good. Text color should consider current skin (dark or lite). Just display the app release semantic version. Text should auto snap to bottom left corner of screen.

![Screen Shot 2021-07-05 at 8 22 26 PM](https://user-images.githubusercontent.com/96002/124503916-2560c600-ddcf-11eb-913c-7e5e0931e4f1.png)

**Comment by lrettig** [comment]
The nice thing about its being on the main screen is that, when users send
us screenshots/screengrabs of issues, we would always know which version
they're running. I think it's okay to always display the version on the
main screen while we're in testnet/testing/pre-genesis phase. Later it
could be moved to, e.g., the top of the Settings screen.

**Comment by avive** [comment]
FYI, with the current implementation, the version text is cramped (no proper padding around text) with the main screen content when the window is in min size. We will deal with it as part of global layout and sizes fixes which is a broader issue.

![Screen Shot 2021-07-07 at 11 40 46 AM](https://user-images.githubusercontent.com/96002/124728401-3cf79600-df18-11eb-80df-701ad25201b5.png)

**Comment by avive** [comment]
Version string is not displayed in some cases in the dash screen. To repro, try to resize the main window in the dash screen.
I don't think this issue is worth opening as the solution is likely good enough for bug reporting regarding all other screens but maybe we'll open this issue again in the future for further polish.

![Screen Shot 2021-07-07 at 11 43 50 AM](https://user-images.githubusercontent.com/96002/124728884-9f509680-df18-11eb-90a7-e7dd10e6cf58.png)
