### ISSUE TITLE
SMD -> Smidge

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#738]
Change Smidge coin symbol from `SMG` to `SDG` everywhere.

**Comment by noamnelke** [comment]
Might I suggest NOT using `SDG` and using the word `Smidge` instead?

Any 3-letter symbol in capital letters, starting with S will get confused with `SMH`. Since smidges are never going to be traded on exchanges, I think that we shouldn't use a symbol for them at all.

**Comment by avive** [comment]
this is the current community recommendation - please raise objections with community.

**Comment by noamnelke** [comment]
I just talked to Alon about it and we'll keep discussing next week. I generally think that since smidges are not traded on exchanges they should not be represented with a 3-uppercase-letter symbol. In bitcoin there's `BTC` (some exchanges list it as `XBT` but that's a different story) and satoshis are either `sat.` (lowercase) or just `satoshi`. I've never seen `SAT` or `STS` used anywhere.

Note that even in Ethereum, where gwei is used extensively - it's never capitalized.

**Comment by avive** [comment]
We want to change the `SMD` symbol to `Smidge` and don't use other symbols besides Smidges and SMH.

**Comment by brusherru** [comment]
@avive what about "GSMD" and "MSMD"?

**Comment by avive** [comment]
We want to get rid of these and only use Smidge or SMH - they were mostly confusing users. We need to make sure that there's enough space for legible large amounts of smidge and do smart formatting for displayed amounts according to this rule: `if an amount is at least 0.0001 SMH then display it in SMH units, otherwise in Smidge`. We also want to have a hover popup over amounts displayed in Smesh that show the amount in Smidge units.

**Comment by avive** [comment]
We also need to sort amount amount inputs but I'm not sure we'll manage to do this for 0.2. Ideally, every text box that accepts an amount has on its right a unit name (Smidge or SMH) and a drop down that allows the user to change between these units, so users will always be able to easily enter an amount with Smidge or with SMH. The default should be SMH units but for testnet timeframe it is likely that smaller Smidge transactions will be popular. Gas price input textbox should default to Smidge and not to SMH but user should still be able to click on the unit name and switch to SMH from Smidge.

**Comment by avive** [comment]
Technically, this issue is for the v0.3 milestone and not for v0.2 but it will be great to have it in v0.2 if all other v0.2 known issues are fixed.

**Comment by avive** [comment]
Regarding amounts input. Something like this:

![Screen Shot 2021-08-17 at 3 01 16 PM](https://user-images.githubusercontent.com/96002/129722140-018fdd6c-b197-4c55-a1fd-5100f6bc6478.png)

**Comment by noamnelke** [comment]
Worth noting that if smidges are entered, a decimal point should not be allowed (but it should be allowed for SMH).

**Comment by brusherru** [comment]
I have an idea how to improve the UX of the amounts input.

Since we got only two units it looks like DropDown is overkill with the worst UX (User interaction: aim on dropdown, click, aim on option, click). So I have an idea to replace it with just a button (User interaction: aim on button, click).

At the first glance, it might be confusing (when you click on it -> what you will get?) or it needs some tips and everything becomes more complicated. But changing units converts the value of the input as well. So it can’t break the user-entered data and he can click on it as much as he wants. After this first experience, he will learn that clicking on the unit (SMH/Smidge) will change it to another one.

If it sounds reasonable and you agree with that idea, I have only one question:
The appearance of the button should make it clear that this button can be clicked: text-underline or bg color, or icon. I think that an icon like "refresh" (curved arrow) next to the units can make sense. What do you prefer? In the case of the icon, I need this icon to be drawn.

**Comment by avive** [comment]
I think it is a good idea although a drop-down with 2 options is not that bad. We can have a rotate icon next to the unit name and clock on it just rotates between the 2 possible values. Otherwise users won't understand this is a button. So basically your refresh idea but it is a rotate...

Something like this on the right-side of the unit label:

![image](https://user-images.githubusercontent.com/96002/130223952-65867d49-c857-4b0a-ae0f-48d76c02d4e0.png)

**Comment by brusherru** [comment]
A small demo (without icon yet):
![output](https://user-images.githubusercontent.com/1897530/130227811-a95876f5-df4b-48b4-a902-460ed18db54b.gif)
The bottom input is a previous one and it will be removed.

**Comment by lrettig** [comment]
I think we're all in agreement here at this point but just to reiterate: please, please do not use the symbols "SMD" or "SDG" anywhere. I agree that "smidge" does not need a ticker symbol and it's much clearer without one.

**Comment by brusherru** [comment]
By the way, do we need to use some library to work with more precision on big numbers (BigInt / BigFloat / etc)?

E.G.:
- 1 SMH -> 1000000000000 Smidge (ok)
- 1000000000001 Smidge -> 1.000000000001 SMH (ok)
- 1.000000000001 SMH -> 1000000000002 Smidge (!!! lost precision !!!)
- 1234567.000000000001 SMH -> 1234567000000000000 Smidge (!!! lost precision !!!)
- 9999999999.990002 SMH -> 9.99999999999e+21 Smidge (scientific notation, lost precision, not user-friendly)

**Comment by avive** [comment]
I think you can use the built-in BigInt type https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt - there used to be several libs from the eth world but now this seems to have moved into the core javascript language inspired by crypto which is great.

**Comment by avive** [comment]
> I think we're all in agreement here at this point but just to reiterate: please, please do not use the symbols "SMD" or "SDG" anywhere. I agree that "smidge" does not need a ticker symbol and it's much clearer without one.

As stated above, we are only going to have 2 supported units in smapp: Smidge and SMH and support input of amount in both and smart display of amounts based on amount size.

**Comment by noamnelke** [comment]
I like the idea of getting rid of the dropdown, but I think that @brusherru's suggestion can be improved.

Since we're on desktop and not very limited in space, why not display both options, and also make it clearer that they're clickable buttons?

Something along these lines:
![image](https://user-images.githubusercontent.com/776358/130345793-53f2d70c-a420-4f8a-bf52-62ecfdac48e0.png)

The design can clearly be improved, but this type of control is more intuitive IMHO.

**Comment by avive** [comment]
@vomcent - please provide visual design and add it to the ui kit / figma. thanks!

**Comment by avive** [comment]
i think we can go ahead with the toggle and apply final design once we get it from vince.

**Comment by vomcent** [comment]
![Arrow Toggle Black](https://user-images.githubusercontent.com/49878947/130509980-dcf0c762-dc62-41bd-8d2f-287cf8a69a3d.png)
![Arrow Toggle White](https://user-images.githubusercontent.com/49878947/130509982-e760bb37-cc97-47da-82db-49712814ac97.png)

White and Black designs attached. I scaled these based on the existing UI kits but let me know if you need a specific size change or something like that. 

Can be found on the UI kit [here](https://www.figma.com/file/6bbFkIAzVu36bIpUNnMqoy/Smapp-Designs?node-id=8471%3A37718) next to the original arrow/bullet point symbol entry.

**Comment by brusherru** [comment]
Is it good enough? 🤔 
![amount-demo](https://user-images.githubusercontent.com/1897530/130623456-264a2911-5711-4ce9-9f81-9dc28b6dac47.gif)

**Comment by avive** [comment]
@vomcent we'd like to use a simple toggle and not a button - can you please provide design for it?

**Comment by brusherru** [comment]
Also, pay attention, that we actually have limited space.
The layout has a fixed size, so the input width is always the same, as in the picture above.
So If we just place two buttons one next to another we can't see the full amount even it will be `0.005 SMH` in Smidge units... 🤔

**Comment by avive** [comment]
This is one of the reasons I originally proposed a drop-down - fixed sized layout considerations...
