### ISSUE TITLE
Feature: add auto detection for blocks on the Settings page

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#913]
The left navigation bar doesn't respond when the page is scrolling, only working with a click

https://user-images.githubusercontent.com/54288612/170369041-40233756-2d89-4bd8-a4d8-984cfeb11dce.mov

**Comment by avive** [comment]
This is a nice catch!

**Comment by brusherru** [comment]
Actually, I'd like to change the Settings screen completely, because now it is quite inconvenient to use.
Moreover, I think most of the things here can fit on just one screen.
Something like this:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/1897530/171104350-e2c0924e-997d-4510-9c74-e0a4c909ba7d.png">

Also, I think it will look correspond with our modern website.

What do you think?
cc: @avive @oriya

**Comment by oriya** [comment]
That is a great idea @brusherru I am 100% supportive of this idea. New Issue? :)

**Comment by avive** [comment]
My 2 cents: I'm not a fan of this approach because it is not very scalable and it makes it hard to add new settings. The current view is not that pretty but is quite functional and similar pattern to other highly popular apps with many settings - check facebook, insta, twitter, chrome. I think it is a good idea once the Settings stabilize a bit more - I think it is likely that this will happen after sm 0.3 core and api will progress a bit.

**Comment by avive** [comment]
Settings is where people go to change defaults and they spend very little time there - in and out - it doesn't make sense to invest in super cool ui in this screen compared to wallet, txs view, rewards stuff, etc... where it is likely that users will spend most of their time in the app...

**Comment by oriya** [comment]
okay. so we wait for now. specifically on redesigning settings. but we will revisit once we are most stable overall.

**Comment by maparr** [comment]
Hey @oriya , @avive , just didn't notice that you're going to rethink this page and just did the task, how it's working after the fix u can take a look https://github.com/spacemeshos/smapp/pull/916 , if we want to change this scree I will close the PR.

**Comment by brusherru** [comment]
> is not very scalable
it might be scalable, at least we can put all "other" stuff in the rows below
but all main features will be on the fingertips, aka it is already on the screen, you don't have to scroll or aim at a corresponding section link :)

Of course, this is not high-priority stuff.
