### ISSUE TITLE
Add semvir to wallet json 

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#983]
Currently, we have a wallet file that we generating depends on the wallet type. I think we have to declare the wallet file structure and add versioning. To be ready for the future change the structure.

maybe exists already some new way to manage files that we store on the client's computer.

WDYT?
cc: @lrettig , @dshulyak , @brusherru

**Comment by brusherru** [comment]
I believe that we don't need to add any version fields there until:
1. we release it in production: afterward we'd have to support all versions / write migrations / etc
2. wallet version cannot be derived from its shape/structure

In the rest, we have a [SMIP#17](https://github.com/spacemeshos/SMIPS/issues/17) that represents a wallet file.
If you need to change something due to new features (e.g. HD Wallets, different account types, support hardware wallets, etc) — you can write a proposal in that SMIP.
Let's keep all the related ideas / proposals / decisions in one place :)
